name: vision_vox
description: Assistive app for visually impaired (Vision Vox)
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  tflite_flutter: ^0.11.0
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_tts: ^4.2.3
  shared_preferences: ^2.2.3
  web_socket_channel: ^3.0.3
  connectivity_plus: ^7.0.0
  permission_handler: ^12.0.1
  camera: ^0.11.2
  image: ^4.1.3 
  image_picker: ^1.1.2
  google_mlkit_text_recognition: ^0.15.0
  # For future on-device OCR/Object Detection (uncomment when you’re ready)
  # google_mlkit_text_recognition: ^0.12.0
  # google_mlkit_object_detection: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/model_unquant.tflite
    - assets/models/labels.txt
